spring.application.name=mealmate-admin-api
---
spring:
  config:
    activate:
      on-profile: dev

jwt:
  header: ${JWT_HEADER}
  secret: ${JWT_SECRET_KEY}
  token-validity-in-seconds: ${JWT_EXPIRATION}